### PR TITLE
updated phpstorm to version 9.0

### PR DESCRIPTION
**Pull request by limatheus**

### CODE REVIEW

**Comment by rafaelstz** [comment]
Thanks for report! :smile: :+1:

**Comment by rafaelstz** [comment]
**English:** Can you create a new installation for this version? It would be interesting to keep both for now!

**Portuguese:** Você poderia criar uma nova instalação para esta versão? Seria interessante manter as duas por enquanto!

**Comment by limatheus** [comment]
:+1: Ok, i do it

**Comment by rafaelstz** [comment]
Thanks for collaboration! I'll be waiting.

**Pull request closed without merging**
